name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: docker build . --file Dockerfile-en --build-arg NPM_TOKEN=$NPM_TOKEN --no-cache --tag tiledesk-server-enterprise:$(date +%s)
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tiledeskrepo/tiledesk-server-enterprise
        tags: latest
